### ISSUE TITLE
[Feature]상품 상세화면 개선하기

### ISSUE THREAD

**Issue by kimjinsub1217** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team3#49]
## Description
- 상품 상세화면 UI 개선하기

## Todo
- [x] 브랜드 데이터 가져와 넣기
- [x] chip 크기라든지 text 크기를 개선하기
- [x] favorite 버튼 lottie 라이브러리 적용

## ETC
기타사항
