### ISSUE TITLE
[Feature][사용자용] 마이페이지 ui / hint ui처리 / 구매 페이지 기본 배송지 있으면 배송지 표시 

### ISSUE THREAD

**Issue by wktkdandp** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team3#56]
## Description
hint 가 겹쳐서 표시되는거 수정
기본 배송지 체크하면 DB에 올리기 / AutoLogin처럼 처리  둘 중 골라서 처리

## Todo
- [x] 마이페이지 ui 수정
- [ ] hint ui 처리
- [ ] 기본 배송지 표시 처리
