### ISSUE TITLE
[Fix] 자잘한 수정사항

### ISSUE THREAD

**Issue by gayeon00** [APPSCHOOL2-Android/FinalProject-ShoppingMallService-team3#94]
## Description
마무리단계

## Todo
- [x] 사용자용 마이페이지 주문목록 이동 카드뷰 손보기
- [x] 사용자용 마이페이지 ui 다듬기
- [x] 주문 완료 페이지에 버튼 활성화하기

## ETC
기타사항
